import{s as u,i as d}from"./assets/vendor-WqaqsYQY.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();function f(a){const s=new URLSearchParams({key:"46272240-cb3616e4f216aad50124ac1b5",q:a,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:21});return fetch(`https://pixabay.com/api/?${s.toString()}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function m(a){if(a.length===0)throw new Error(response);return a.map(e=>`<li class="gallery-object">
    <a href='${e.largeImageURL}' class="simple-gal"><img src='${e.webformatURL}' class="gallery-image" alt='${e.tags}' /></a>
    <ul class="gallery-stats">
    <li class="gallery-stats-likes">Likes <span>${e.likes}</span></li>
    <li class="gallery-stats-views">Views <span>${e.views}</span></li>
    <li class="gallery-stats-comments">Comments <span>${e.comments}</span></li>
    <li class="gallery-stats-downloads">Downloads <span>${e.downloads}</span></li>
    </ul>
    </li>`).join("")}const n=document.querySelector("form"),l=document.querySelector(".gallery-list"),c=document.querySelector(".loader"),p=new u(".simple-gal",{captionsData:"alt"});function g(){c.classList.remove("is-hidden")}function h(){c.classList.add("is-hidden")}function y(a){a.preventDefault(),l.innerHTML="",g(),f(n[0].value).then(s=>{h();const e=s.hits;l.insertAdjacentHTML("beforeend",m(e))}).then(()=>{p.refresh()}).catch(s=>{d.error({message:"Sorry, there are no images matching your search query. Please try again!"})}),n.reset()}n.addEventListener("submit",y);
//# sourceMappingURL=index.js.map
