import{s as c,i as u}from"./assets/vendor-WqaqsYQY.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function e(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=e(r);fetch(r.href,s)}})();function p(a){const t=new URLSearchParams({key:"46272240-cb3616e4f216aad50124ac1b5",q:a,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:21});return fetch(`https://pixabay.com/api/?${t.toString()}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function m(a){if(a.length===0)throw new Error(response);return a.map(e=>`<li class="gallery-object">
    <a href='${e.largeImageURL}' class="simple-gal"><img src='${e.webformatURL}' class="gallery-image" alt='${e.tags}' /></a>
    <ul class="gallery-stats">
    <li class="gallery-stats-likes">Likes <span>${e.likes}</span></li>
    <li class="gallery-stats-views">Views <span>${e.views}</span></li>
    <li class="gallery-stats-comments">Comments <span>${e.comments}</span></li>
    <li class="gallery-stats-downloads">Downloads <span>${e.downloads}</span></li>
    </ul>
    </li>`).join("")}const l=document.querySelector("form"),o=document.querySelector(".gallery-list");function f(a){a.preventDefault(),o.innerHTML='<span class="loader"></span>',p(l[0].value).then(t=>{o.innerHTML="";const e=t.hits;return o.insertAdjacentHTML("beforeend",m(e)),new c(".simple-gal",{captionsData:"alt"})}).then(t=>{t.refresh()}).catch(t=>{u.error({message:"Sorry, there are no images matching your search query. Please try again!"})}),l.reset()}l.addEventListener("submit",f);
//# sourceMappingURL=index.js.map
